export const JAMIYYAH_LIST = [
  "AL-ALIYAH",
  "AL-SA'IDIYYAH",
  "AL-FATHIYYAH",
  "AL-ISHOMIYYAH",
  "AL-FALAHIYAH",
  "AL-AZHAR",
  "AL-AQSHO",
  "AL-MUSTHOFA",
  "AZ-ZAMZAMIYAH",
  "AL-AZIZIYYAH",
  "DALEM",
  "TAMATAN 2027",
];
